### ISSUE TITLE
조근석 석사 졸업 축하합니다!!

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/aiml-k.github.io#48]
Congratulations @hamgcho!!  

### TODO

- [x] add news to lab website - @d-h-lee 
- [ ] move hamgcho to alumni - @d-h-lee 
- [ ] update hamgcho's intro / CV / and photo - @hamgcho and @d-h-lee

**Comment by d-h-lee** [comment]
partly resolved by #49

**Comment by d-h-lee** [comment]
Resolved by #55
