### ISSUE TITLE
Advertise AIML@K fall 2024 seminar 

### ISSUE THREAD

**Issue by d-h-lee** [AIML-K/aiml-k.github.io#50]
### TODO

- [ ] update date (9/27 -> 9/6)
- [ ] add link to the seminar website (google sites)
- [ ] confirm the location + update the event
- [ ] send out emails to 수학과, 이과대학

**Comment by d-h-lee** [comment]
The event is complete, and need to update the page at https://aiml-k.github.io/event/24-09-27-aimlk_fall_workshop_2024/
